### ISSUE TITLE
Download failed with error 404 for: //zlib.net/zlib-1.2.11.tar.gz 

### ISSUE THREAD

**Issue by psammarco** [statgen/savvy#25]
Hello @CreRecombinase ,

I am trying to install SAIGE which pulls savvy as cget dependency. However savvy fails to build as result of a dead zlib link.

could you please fix the bit of the code that points to a dead zlib link?

```
Downloading http://zlib.net/zlib-1.2.11.tar.gz
  [----------------------------------------------------------------------]    0%
Download failed with error 404 for: //zlib.net/zlib-1.2.11.tar.gz
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/usr/local/lib/R/site-library/SAIGE’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpE6Jk4z/file2b3272197cc98/SAIGE_0.42.1.tar.gz’ had non-zero exit status
>
```

The correct link is https://zlib.net/fossils/zlib-1.2.11.tar.gz

Regards

**Comment by jonathonl** [comment]
Yes, this has been fixed in the master branch of Savvy, but SAIGE is not using the latest commit. You can get around this by taking the following steps.
1. Remove line 20 (https://github.com/weizhouUMICH/SAIGE/blob/master/configure#L20) from the configure script.
2. Run`cget install -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" --prefix thirdParty/cget https://zlib.net/fossils/zlib-1.2.11.tar.gz`.
3. Run the the normal install command (`R CMD INSTALL --library=path_to_final_SAIGE_library SAIGE`).

**Comment by psammarco** [comment]
Hello, apparently removing just line 20 didn't seem to be enough. I removed line 19 to line 22 and did the trick. 

Thank you!
