### ISSUE TITLE
sav export vcf / AF is updated MAF not

### ISSUE THREAD

**Issue by ilarsf** [statgen/savvy#6]
Hi Jonathon,

when I export a subset with
`sav export --sample-ids <SAMPLE ID> --file-format vcf <in.sav> <out.vcf>`
I found that savvy updated the INFO/AF which is a great feature. However, the INFO/MAF remained unchanged.

FYI: I'm using the latest savvy version in your home directory 

Cheers,
Lars

**Comment by jonathonl** [comment]
Yeah, I can add MAF to the auto-generated fields. Currently, it's only AC, AN and AF for GT data and AF for HDS.

**Comment by jonathonl** [comment]
Fixed in 5bdc40848abf266c1e04170271707ec0a8f287f3. 

Note:  A new option (--update-info) has been added to import and export. The default is auto, but it can also be set to always or never. Auto will update the info fields when subsetting samples, so there is no need to actually specify --update-info unless you need to force update a file with incorrect info fields.
